### ISSUE TITLE
Error while initiating vagrant

### ISSUE THREAD

**Issue by gugho** [0xffsec/webdojo#1]
Vagrant returns an error while Initiating the box.

```
         11: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/plugins/providers/virtualbox/driver/base.rb:425:in `raise'
         10: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/plugins/providers/virtualbox/driver/base.rb:425:in `exception'
          9: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/errors.rb:72:in `initialize'
          8: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/errors.rb:103:in `translate_error'
          7: from /usr/share/rubygems-integration/all/gems/i18n-1.8.2/lib/i18n.rb:202:in `translate'
          6: from /usr/share/rubygems-integration/all/gems/i18n-1.8.2/lib/i18n.rb:202:in `catch'
          5: from /usr/share/rubygems-integration/all/gems/i18n-1.8.2/lib/i18n.rb:206:in `block in translate'
          4: from /usr/share/rubygems-integration/all/gems/i18n-1.8.2/lib/i18n/backend/base.rb:61:in `translate'
          3: from /usr/share/rubygems-integration/all/gems/i18n-1.8.2/lib/i18n/backend/base.rb:187:in `interpolate'
          2: from /usr/share/rubygems-integration/all/gems/i18n-1.8.2/lib/i18n/interpolate/ruby.rb:19:in `interpolate'
          1: from /usr/share/rubygems-integration/all/gems/i18n-1.8.2/lib/i18n/interpolate/ruby.rb:23:in `interpolate_hash'
/usr/share/rubygems-integration/all/gems/i18n-1.8.2/lib/i18n/interpolate/ruby.rb:23:in `gsub': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
```

**Comment by maxrodrigo** [comment]
Can't replicate.
